### ISSUE TITLE
Can not compile in Xcode Version 12.0 (12A7209)

### ISSUE THREAD

**Issue by neetin** [UnifyID/unifyid-ios-sdk#1]
Details:
<img width="1126" alt="Screen Shot 2020-09-18 at 23 14 01" src="https://user-images.githubusercontent.com/386799/93627658-faa2ae00-fa04-11ea-8258-14b6cc4a359e.png">

**Comment by mrosales** [comment]
Hi @neetin, we've been working on fixing builds in Xcode 12. The `UnifyID` frameworks need to get re-built with `Xcode 12` to solve the problem you are seeing here, and we've hit a couple of issues with upstream dependencies also being incompatible.

I'm anticipating a fix for this to be ready in the next couple of days. We'll post another update here when the release is out.

**Comment by lamielle** [comment]
Hi @neetin, thanks for reporting this issue!  I wanted to let you know that we just pushed out a new set of releases for the iOS SDK that should resolve the issue you've reported here:

- GaitAuth 4.3.0
- PushAuth 3.2.0
- HumanDetect 3.2.0

If you update to one of these releases you should be unblocked (it depends on what SDK you were attempting to use, though I expect it was GaitAuth).

I'll leave this issue open until I hear back from you that the latest release is working for you in Xcode 12.

**Comment by neetin** [comment]
Hi @lamielle @mrosales This issue is fixed.
Thanks!

**Comment by lamielle** [comment]
Thanks for confirming @neetin!  🎉   Glad it's working for you now.  Let us know if you have any other questions or run into any other issues!
